apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    name: logs-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: logs-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
