apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    name: media-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/revolman/kubernetes/storage/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      name: media-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
...
